name: agendarcampos

services:
  mariadb:
    image: mariadb:latest
    container_name: agendarcampos
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: agendarcampos
    ports:
      - "3306:3306"
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge